version: '3.9'
services: 
  nest-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-db
    networks:
      - freecodecamp
networks:
  freecodecamp: